<template>
  <DataTable :rows="xrow" :columns="xcol" />
</template>

<script>
import DataTable from "@/components/DataTable";

export default {
  name: "Applied Leaves",
  components: {
    DataTable,
  },
  data() {
    return {
      xrow: [
        {
          id: 1,
          leaveType: "Sick",
          startDate: "4/8/2020",
          endDate: "4/11/2020",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 2,
          leaveType: "Casual",
          startDate: "7/4/2020",
          endDate: "7/9/2020",
          status: "Rejected",
          leaves: 5,
        },
        {
          id: 3,
          leaveType: "Casual",
          startDate: "6/26/2020",
          endDate: "7/1/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 4,
          leaveType: "Sick",
          startDate: "4/24/2021",
          endDate: "4/26/2021",
          status: "Rejected",
          leaves: 2,
        },
        {
          id: 5,
          leaveType: "Annual",
          startDate: "10/8/2020",
          endDate: "10/12/2020",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 6,
          leaveType: "Annual",
          startDate: "7/24/2020",
          endDate: "7/25/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 7,
          leaveType: "Sick",
          startDate: "5/6/2021",
          endDate: "5/7/2021",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 8,
          leaveType: "Casual",
          startDate: "4/16/2021",
          endDate: "4/19/2021",
          status: "Pending",
          leaves: 3,
        },
        {
          id: 9,
          leaveType: "Annual",
          startDate: "4/8/2021",
          endDate: "4/9/2021",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 10,
          leaveType: "Annual",
          startDate: "8/17/2020",
          endDate: "8/19/2020",
          status: "Approved",
          leaves: 2,
        },
        {
          id: 11,
          leaveType: "Annual",
          startDate: "5/28/2020",
          endDate: "5/30/2020",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 12,
          leaveType: "Casual",
          startDate: "4/4/2020",
          endDate: "4/5/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 13,
          leaveType: "Sick",
          startDate: "2/5/2021",
          endDate: "2/10/2021",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 14,
          leaveType: "Annual",
          startDate: "12/20/2020",
          endDate: "12/24/2020",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 15,
          leaveType: "Sick",
          startDate: "7/27/2020",
          endDate: "8/1/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 16,
          leaveType: "Casual",
          startDate: "6/1/2021",
          endDate: "6/4/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 17,
          leaveType: "Sick",
          startDate: "9/7/2020",
          endDate: "9/10/2020",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 18,
          leaveType: "Casual",
          startDate: "1/1/2021",
          endDate: "1/6/2021",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 19,
          leaveType: "Casual",
          startDate: "2/12/2021",
          endDate: "2/15/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 20,
          leaveType: "Sick",
          startDate: "4/1/2020",
          endDate: "4/2/2020",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 21,
          leaveType: "Sick",
          startDate: "7/24/2020",
          endDate: "7/28/2020",
          status: "Pending",
          leaves: 4,
        },
        {
          id: 22,
          leaveType: "Annual",
          startDate: "4/1/2021",
          endDate: "4/2/2021",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 23,
          leaveType: "Annual",
          startDate: "5/5/2021",
          endDate: "5/8/2021",
          status: "Pending",
          leaves: 3,
        },
        {
          id: 24,
          leaveType: "Casual",
          startDate: "4/26/2020",
          endDate: "4/30/2020",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 25,
          leaveType: "Sick",
          startDate: "1/24/2021",
          endDate: "1/26/2021",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 26,
          leaveType: "Sick",
          startDate: "9/12/2020",
          endDate: "9/13/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 27,
          leaveType: "Sick",
          startDate: "2/10/2021",
          endDate: "2/13/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 28,
          leaveType: "Casual",
          startDate: "9/6/2020",
          endDate: "9/7/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 29,
          leaveType: "Sick",
          startDate: "7/10/2021",
          endDate: "7/12/2021",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 30,
          leaveType: "Casual",
          startDate: "7/31/2021",
          endDate: "8/5/2021",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 31,
          leaveType: "Annual",
          startDate: "2/12/2021",
          endDate: "2/14/2021",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 32,
          leaveType: "Annual",
          startDate: "3/12/2021",
          endDate: "3/14/2021",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 33,
          leaveType: "Annual",
          startDate: "4/17/2021",
          endDate: "4/19/2021",
          status: "Rejected",
          leaves: 2,
        },
        {
          id: 34,
          leaveType: "Casual",
          startDate: "8/9/2020",
          endDate: "8/12/2020",
          status: "Approved",
          leaves: 3,
        },
        {
          id: 35,
          leaveType: "Casual",
          startDate: "5/4/2020",
          endDate: "5/8/2020",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 36,
          leaveType: "Casual",
          startDate: "6/5/2020",
          endDate: "6/9/2020",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 37,
          leaveType: "Annual",
          startDate: "4/8/2020",
          endDate: "4/13/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 38,
          leaveType: "Casual",
          startDate: "5/16/2021",
          endDate: "5/19/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 39,
          leaveType: "Casual",
          startDate: "6/23/2021",
          endDate: "6/25/2021",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 40,
          leaveType: "Annual",
          startDate: "12/27/2020",
          endDate: "1/1/2021",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 41,
          leaveType: "Sick",
          startDate: "5/23/2021",
          endDate: "5/28/2021",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 42,
          leaveType: "Annual",
          startDate: "12/29/2020",
          endDate: "12/30/2020",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 43,
          leaveType: "Sick",
          startDate: "1/14/2021",
          endDate: "1/18/2021",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 44,
          leaveType: "Casual",
          startDate: "5/27/2020",
          endDate: "6/1/2020",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 45,
          leaveType: "Sick",
          startDate: "5/27/2020",
          endDate: "5/30/2020",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 46,
          leaveType: "Annual",
          startDate: "4/3/2021",
          endDate: "4/8/2021",
          status: "Rejected",
          leaves: 5,
        },
        {
          id: 47,
          leaveType: "Sick",
          startDate: "7/8/2020",
          endDate: "7/13/2020",
          status: "Rejected",
          leaves: 5,
        },
        {
          id: 48,
          leaveType: "Annual",
          startDate: "4/30/2021",
          endDate: "5/2/2021",
          status: "Rejected",
          leaves: 2,
        },
        {
          id: 49,
          leaveType: "Sick",
          startDate: "12/7/2020",
          endDate: "12/8/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 50,
          leaveType: "Annual",
          startDate: "4/25/2021",
          endDate: "4/28/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 51,
          leaveType: "Casual",
          startDate: "3/21/2021",
          endDate: "3/25/2021",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 52,
          leaveType: "Casual",
          startDate: "8/14/2020",
          endDate: "8/16/2020",
          status: "Rejected",
          leaves: 2,
        },
        {
          id: 53,
          leaveType: "Sick",
          startDate: "5/1/2020",
          endDate: "5/6/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 54,
          leaveType: "Annual",
          startDate: "10/21/2020",
          endDate: "10/26/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 55,
          leaveType: "Annual",
          startDate: "9/30/2020",
          endDate: "10/4/2020",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 56,
          leaveType: "Casual",
          startDate: "4/1/2020",
          endDate: "4/5/2020",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 57,
          leaveType: "Sick",
          startDate: "6/23/2020",
          endDate: "6/24/2020",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 58,
          leaveType: "Annual",
          startDate: "6/9/2021",
          endDate: "6/11/2021",
          status: "Approved",
          leaves: 2,
        },
        {
          id: 59,
          leaveType: "Casual",
          startDate: "2/12/2021",
          endDate: "2/15/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 60,
          leaveType: "Casual",
          startDate: "4/7/2021",
          endDate: "4/12/2021",
          status: "Rejected",
          leaves: 5,
        },
        {
          id: 61,
          leaveType: "Annual",
          startDate: "1/1/2021",
          endDate: "1/2/2021",
          status: "Rejected",
          leaves: 1,
        },
        {
          id: 62,
          leaveType: "Sick",
          startDate: "9/2/2020",
          endDate: "9/6/2020",
          status: "Pending",
          leaves: 4,
        },
        {
          id: 63,
          leaveType: "Annual",
          startDate: "7/21/2020",
          endDate: "7/24/2020",
          status: "Pending",
          leaves: 3,
        },
        {
          id: 64,
          leaveType: "Casual",
          startDate: "6/14/2021",
          endDate: "6/17/2021",
          status: "Pending",
          leaves: 3,
        },
        {
          id: 65,
          leaveType: "Casual",
          startDate: "5/24/2021",
          endDate: "5/25/2021",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 66,
          leaveType: "Sick",
          startDate: "8/6/2020",
          endDate: "8/7/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 67,
          leaveType: "Casual",
          startDate: "5/31/2021",
          endDate: "6/1/2021",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 68,
          leaveType: "Annual",
          startDate: "6/1/2020",
          endDate: "6/2/2020",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 69,
          leaveType: "Casual",
          startDate: "5/8/2020",
          endDate: "5/13/2020",
          status: "Rejected",
          leaves: 5,
        },
        {
          id: 70,
          leaveType: "Sick",
          startDate: "1/16/2021",
          endDate: "1/20/2021",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 71,
          leaveType: "Sick",
          startDate: "5/9/2021",
          endDate: "5/14/2021",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 72,
          leaveType: "Casual",
          startDate: "8/18/2020",
          endDate: "8/21/2020",
          status: "Pending",
          leaves: 3,
        },
        {
          id: 73,
          leaveType: "Sick",
          startDate: "7/7/2020",
          endDate: "7/8/2020",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 74,
          leaveType: "Sick",
          startDate: "10/11/2020",
          endDate: "10/16/2020",
          status: "Rejected",
          leaves: 5,
        },
        {
          id: 75,
          leaveType: "Annual",
          startDate: "7/14/2020",
          endDate: "7/19/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 76,
          leaveType: "Casual",
          startDate: "4/14/2021",
          endDate: "4/16/2021",
          status: "Rejected",
          leaves: 2,
        },
        {
          id: 77,
          leaveType: "Sick",
          startDate: "10/30/2020",
          endDate: "10/31/2020",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 78,
          leaveType: "Sick",
          startDate: "4/16/2020",
          endDate: "4/18/2020",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 79,
          leaveType: "Annual",
          startDate: "7/19/2020",
          endDate: "7/24/2020",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 80,
          leaveType: "Sick",
          startDate: "5/16/2021",
          endDate: "5/20/2021",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 81,
          leaveType: "Annual",
          startDate: "4/6/2020",
          endDate: "4/7/2020",
          status: "Rejected",
          leaves: 1,
        },
        {
          id: 82,
          leaveType: "Sick",
          startDate: "6/29/2020",
          endDate: "7/4/2020",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 83,
          leaveType: "Sick",
          startDate: "9/8/2020",
          endDate: "9/9/2020",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 84,
          leaveType: "Annual",
          startDate: "6/24/2020",
          endDate: "6/29/2020",
          status: "Pending",
          leaves: 5,
        },
        {
          id: 85,
          leaveType: "Annual",
          startDate: "3/25/2021",
          endDate: "3/29/2021",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 86,
          leaveType: "Sick",
          startDate: "6/26/2021",
          endDate: "6/28/2021",
          status: "Pending",
          leaves: 2,
        },
        {
          id: 87,
          leaveType: "Annual",
          startDate: "4/15/2020",
          endDate: "4/20/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 88,
          leaveType: "Annual",
          startDate: "5/15/2020",
          endDate: "5/19/2020",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 89,
          leaveType: "Sick",
          startDate: "3/30/2021",
          endDate: "4/3/2021",
          status: "Approved",
          leaves: 4,
        },
        {
          id: 90,
          leaveType: "Casual",
          startDate: "7/3/2021",
          endDate: "7/4/2021",
          status: "Approved",
          leaves: 1,
        },
        {
          id: 91,
          leaveType: "Annual",
          startDate: "6/11/2020",
          endDate: "6/15/2020",
          status: "Rejected",
          leaves: 4,
        },
        {
          id: 92,
          leaveType: "Sick",
          startDate: "11/30/2020",
          endDate: "12/5/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 93,
          leaveType: "Annual",
          startDate: "3/23/2021",
          endDate: "3/24/2021",
          status: "Pending",
          leaves: 1,
        },
        {
          id: 94,
          leaveType: "Sick",
          startDate: "3/24/2021",
          endDate: "3/27/2021",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 95,
          leaveType: "Casual",
          startDate: "7/15/2021",
          endDate: "7/20/2021",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 96,
          leaveType: "Casual",
          startDate: "7/16/2020",
          endDate: "7/17/2020",
          status: "Rejected",
          leaves: 1,
        },
        {
          id: 97,
          leaveType: "Annual",
          startDate: "6/16/2021",
          endDate: "6/18/2021",
          status: "Approved",
          leaves: 2,
        },
        {
          id: 98,
          leaveType: "Casual",
          startDate: "5/3/2021",
          endDate: "5/5/2021",
          status: "Approved",
          leaves: 2,
        },
        {
          id: 99,
          leaveType: "Casual",
          startDate: "9/5/2020",
          endDate: "9/8/2020",
          status: "Rejected",
          leaves: 3,
        },
        {
          id: 100,
          leaveType: "Sick",
          startDate: "1/1/2021",
          endDate: "1/2/2021",
          status: "Rejected",
          leaves: 1,
        },
        {
          id: 101,
          leaveType: "Annual",
          startDate: "7/6/2021",
          endDate: "7/10/2021",
          status: "Pending",
          leaves: 4,
        },
        {
          id: 102,
          leaveType: "Annual",
          startDate: "8/15/2020",
          endDate: "8/20/2020",
          status: "Approved",
          leaves: 5,
        },
        {
          id: 103,
          leaveType: "Annual",
          startDate: "5/31/2020",
          endDate: "6/1/2020",
          status: "Rejected",
          leaves: 1,
        },
        {
          id: 104,
          leaveType: "Annual",
          startDate: "9/21/2020",
          endDate: "9/25/2020",
          status: "Pending",
          leaves: 4,
        },
        {
          id: 105,
          leaveType: "Sick",
          startDate: "3/22/2021",
          endDate: "3/26/2021",
          status: "Approved",
          leaves: 4,
        },
      ],
      xcol: [
        {
          field: "id",
          label: "ID",
        },
        {
          field: "leaveType",
          label: "Leave Type",
        },
        {
          field: "startDate",
          label: "Start Date",
        },
        {
          field: "endDate",
          label: "End Date",
        },
        {
          field: "leaves",
          label: "Days",
        },
        {
          field: "status",
          label: "Status",
        },
      ],
    };
  },
};
</script>

<style></style>
